config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/index'
  resources :schedules
  resources :bookings
  resources :packs
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :customer
  belongs_to :booking
  belongs_to :pack
  belongs_to :employee
  validate :clash

  def clash
    clash = Schedule.where(employee_id: employee_id, appointment: (appointment - 1.hour)..(appointment + 1.hour)).present?
    errors.add(:appointment, "Already taken") if clash
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    #@schedules = Schedule.ransack(params[:q])
    @schedules = Schedule.all.order("appointment desc").page params[:page]
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    customer = Customer.find(params[:customer])
    @nearby_employees = Employee.near([customer.latitude, customer.longitude], 20, units: :km)
    @dates = params[:dates].present? ? (session[:dates] || []) : []
  end

  # GET /schedules/1/edit
  def edit
    customer = Customer.find(params[:customer])
    @nearby_employees = Employee.near([customer.latitude, customer.longitude], 20, units: :km)
  end

  # POST /schedules
  # POST /schedules.json
  def create
    begin
      @schedule = Schedule.new(schedule_params)

      respond_to do |format|
        if @schedule.save
          format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
          format.json { render :show, status: :created, location: @schedule }
        else
          format.html { render :new }
          format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end
      end
    rescue NoMethodError
      Schedule.transaction do
        appointments = params[:schedule].count
        session[:dates] = []
        params[:schedule].each do |schedule|
          @schedule = Schedule.new(schedule.permit(:customer_id, :booking_id, :pack_id, :employee_id, :appointment))
          if @schedule.valid?
            session[:dates] << @schedule.appointment
            @schedule.save
          else
            customer = Customer.find(@schedule.customer_id)
            @nearby_employees = Employee.near([customer.latitude, customer.longitude], 20, units: :km)
            @errors = true
            respond_to do |format|
              format.html {redirect_to new_schedule_path(appointments: appointments, customer: @schedule.customer.id, pack: @schedule.pack.id, booking: @schedule.booking.id, dates: "true"), notice: "#{@schedule.employee.name} not available for #{@schedule.appointment.to_formatted_s(:long_ordinal)}"}
            end
            raise ActiveRecord::Rollback
            break
          end
        end
      end
      unless @errors
        respond_to do |format|
          format.html { redirect_to schedules_path, notice: 'Schedule was successfully created.' }
        end
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        customer = Customer.find(@schedule.customer_id)
        @nearby_employees = Employee.near([customer.latitude, customer.longitude], 20, units: :km)
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def schedule_params
    params.require(:schedule).permit(:customer_id, :booking_id, :pack_id, :employee_id, :appointment, :status)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= simple_form_for(@schedule) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%# f.association :customer %>
    <%= f.input :customer_id, as: :hidden, input_html: { value: params[:customer] } %>
    <%= f.input :booking_id, as: :hidden, input_html: { value: params[:booking] } %>
    <%= f.input :pack_id, as: :hidden, input_html: { value: params[:pack] } %>
    <%# f.association :booking %>
    <%# f.association :pack %>
    <%= f.association :employee %>
    <%= f.input :appointment %>
    <%= f.input :status, as: :radio_buttons %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schedules/_nearby.html.erb
<div class="row">
  <table class="responstable">
    <tr>
      <th>Nearby Employees</th>
      <th>Distance</th>
    </tr>
    <% nearby_employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.distance.round(2) %> Kms</td>
      </tr>
    <% end %>
  </table>
</div>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>
<%= render partial: "nearby", locals: {nearby_employees: @nearby_employees} %>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table class="responstable">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Booking</th>
      <th>Pack</th>
      <th>Employee</th>
      <th>Appointment</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.customer.name %></td>
        <td><%= link_to schedule.booking.id, booking_path(schedule.booking) %></td>
        <td><%= schedule.pack.name %></td>
        <td><%= schedule.employee.name %></td>
        <td><%= schedule.appointment.to_formatted_s(:long_ordinal) %></td>
        <td><%= schedule.status %></td>
        <td>
          <%= link_to 'Show', schedule %>
          <%= link_to 'Edit', edit_schedule_path(schedule, customer: schedule.customer.id, pack: schedule.pack.id, booking: schedule.booking.id) %>
          <%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @schedules %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>
<%= render partial: "nearby", locals: {nearby_employees: @nearby_employees} %>
<div class="row">
<p id="notice"><%= notice %></p>
<%= simple_form_for(@schedule) do |f| %>
  <%= f.error_notification %>

  <% params[:appointments].to_i.times do |i|%>
    <div class="form-inputs">
      <%= f.simple_fields_for '[]', Schedule.new do |ff|%>
        <%# f.association :customer %>
        <%# f.association :booking %>
        <%# f.association :pack %>
        <div style="border-style: groove; padding: 10px" class="col-md-6">
          <%= ff.input :appointment, selected: (Time.parse(@dates[i] || Time.now.to_s)) %>
          <%= ff.input :customer_id, as: :hidden, input_html: { value: params[:customer] } %>
          <%= ff.input :booking_id, as: :hidden, input_html: { value: params[:booking] } %>
          <%= ff.input :pack_id, as: :hidden, input_html: { value: params[:pack] } %>
          <%= ff.association :employee, selected: (@nearby_employees.first.id rescue nil) %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>
<table class="responstable">
  <tr>
    <th><strong>Customer</strong></th>
    <th><%= @schedule.customer.name %></th>
  </tr>
  <tr>
    <td><strong>Customer Contact Number</strong></td>
    <td><%= @schedule.customer.contact_number %></td>
  </tr>
  <tr>
    <td><strong>Customer Address</strong></td>
    <td><%= @schedule.customer.address %></td>
  </tr>
  <tr>
    <td><strong>Booking ID</strong></td>
    <td><%= link_to @schedule.booking.id, booking_path(@schedule.booking) %></td>
  </tr>
  <tr>
    <td><strong>Pack</strong></td>
    <td><%= @schedule.pack.name %></td>
  </tr>
  <tr>
    <td><strong>Employee</strong></td>
    <td><%= @schedule.employee.name %></td>
  </tr>
  <tr>
    <td><strong>Appointment</strong></td>
    <td><%= @schedule.appointment.to_formatted_s(:long_ordinal) %></td>
  </tr>
  <tr>
    <td><strong>Status</strong></td>
    <td><%= @schedule.status %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_schedule_path(@schedule, customer: @schedule.customer.id, pack: @schedule.pack.id, booking: @schedule.booking.id) %>
<%= link_to 'Back', schedules_path %>