config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/index'
  resources :schedules
  resources :bookings
  resources :packs
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @schedules = Schedule.all.order("appointment desc")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= month_calendar attribute: :appointment, events: @schedules do |date, schedules| %>
  <h3 style="text-align: center"><%= date.day %></h3>
  <% if schedules.present? %>
    <button class="btn btn-primary btn-sm" type="button" data-toggle="modal" data-target="#content-<%= date.day %>" id="button-<%= date.day %>"><%= schedules.count %> schedules</button>
    <div class="modal fade" id="content-<%= date.day %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Schedules</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <table class="responstable">
              <tr>
                <th>Customer Name</th>
                <th>Employee Name</th>
                <th>Time</th>
              </tr>
              <% schedules.each do |schedule| %>
                <tr>
                  <td><%= schedule.customer.name %></td>
                  <td><%= schedule.employee.name %></td>
                  <td><%= link_to schedule.appointment.strftime("%H:%M %p"), schedule_path(schedule) %></td>
                </tr>
              <% end %>
            </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>