config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/index'
  resources :schedules
  resources :bookings
  resources :packs
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all.page params[:page]
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :contact_number, :alternate_number, :profession, :experience, :enterprise, :age, :sex, :refferal_type, :refferal, :executive, :email, :home_address, :office_address, :amount_pending)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :contact_number %>
    <%= f.input :alternate_number %>
    <%= f.input :profession %>
    <%= f.input :experience %>
    <%= f.input :enterprise %>
    <%= f.input :age, as: :numeric %>
    <%= f.input :sex, collection: ["M","F"] %>
    <%= f.input :refferal_type, collection: ["Medium","Person"] %>
    <%= f.input :refferal %>
    <%= f.input :executive %>
    <%= f.input :email %>
    <%= f.input :vehicle_kind %>
    <%= f.input :vehicle_no %>
    <%= f.input :vehicle_brand %>
    <%= f.input :vehicle_model %>
    <%= f.input :vehicle_color %>
    <%= f.input :vehicle_gear_type %>
    <%= f.input :vehicle_no_of_gears %>
    <%= f.input :vehicle_other %>
    <%= f.input :cab_name %>
    <%= f.input :cab_agent %>
    <%= f.input :cab_rate %>
    <%= f.input :cab_total_distance %>
    <%= f.input :cab_total_fare %>
    <%= f.input :cab_kind %>
    <%= f.input :cab_no %>
    <%= f.input :cab_brand %>
    <%= f.input :cab_model %>
    <%= f.input :cab_color %>
    <%= f.input :cab_gear_type %>
    <%= f.input :cab_no_of_gears %>
    <%= f.input :home_address %>
    <%= f.input :office_address %>
    <%= f.input :location %>
    <%= f.input :current_provider %>
    <%= f.input :requirement %>
    <%= f.input :remarks %>
    <%= f.input :review %>
    <%= f.input :rating %>
    <%= f.input :suggestions %>
    <%= f.input :insights %>
    <%= f.input :to_do %>
    <%= f.input :last_communication %>
    <%= f.input :call_back %>
    <%= f.input :status %>
    <%= f.input :discounts %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>
<%= link_to 'New Customer', new_customer_path %>
<table class="responstable unresponsive">
  <thead>
    <tr>
      <th>Actions</th>
      <th>Name</th>
      <th>Contact number</th>
      <th>Alternate number</th>
      <th>Profession</th>
      <th>Experience</th>
      <th>Enterprise</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Refferal Type</th>
      <th>Refferal</th>
      <th>Executive</th>
      <th>Email</th>
      <th>Home Address</th>
      <th>Office Address</th>
      <th>Vehicle Kind</th>
      <th>Vehicle No</th>
      <th>Vehicle Brand</th>
      <th>Vehicle Model</th>
      <th>Vehicle Color</th>
      <th>Vehicle Gear Type</th>
      <th>Vehicle No of Gears</th>
      <th>Vehicle Other</th>
      <th>Cab Name</th>
      <th>Cab Agent</th>
      <th>Cab Rate</th>
      <th>Cab Total Distance</th>
      <th>Cab Total Fare</th>
      <th>Cab Kind</th>
      <th>Cab No</th>
      <th>Cab Brand</th>
      <th>Cab Model</th>
      <th>Cab Color</th>
      <th>Cab Gear Type</th>
      <th>Cab No of Gears</th>
      <th>Location</th>
      <th>Current Provider</th>
      <th>Requirement</th>
      <th>Remarks</th>
      <th>Review</th>
      <th>Rating</th>
      <th>Suggestions</th>
      <th>Insights</th>
      <th>To Do</th>
      <th>Last Communication</th>
      <th>Call Back</th>
      <th>Status</th>
      <th>Discounts</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td>
          <%= link_to 'Show', customer %>
          <%= link_to 'Edit', edit_customer_path(customer) %>
          <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <td><%= customer.name %></td>
        <td><%= customer.contact_number %></td>
        <td><%= customer.alternate_number %></td>
        <td><%= customer.profession %></td>
        <td><%= customer.experience %></td>
        <td><%= customer.enterprise %></td>
        <td><%= customer.age %></td>
        <td><%= customer.sex %></td>
        <td><%= customer.refferal_type %></td>
        <td><%= customer.refferal %></td>
        <td><%= customer.executive %></td>
        <td><%= customer.email %></td>
        <td><%= customer.home_address %></td>
        <td><%= customer.office_address %></td>
        <td><%= customer.vehicle_kind %></td>
        <td><%= customer.vehicle_no %></td>
        <td><%= customer.vehicle_no %></td>
        <td><%= customer.vehicle_brand %></td>
        <td><%= customer.vehicle_model %></td>
        <td><%= customer.vehicle_color %></td>
        <td><%= customer.vehicle_gear_type %></td>
        <td><%= customer.vehicle_no_of_gears %></td>
        <td><%= customer.vehicle_other %></td>
        <td><%= customer.cab_name %></td>
        <td><%= customer.cab_agent %></td>
        <td><%= customer.cab_rate %></td>
        <td><%= customer.cab_total_distance %></td>
        <td><%= customer.cab_total_fare %></td>
        <td><%= customer.cab_kind %></td>
        <td><%= customer.cab_no %></td>
        <td><%= customer.cab_brand %></td>
        <td><%= customer.cab_model %></td>
        <td><%= customer.cab_color %></td>
        <td><%= customer.cab_gear_type %></td>
        <td><%= customer.cab_no_of_gears %></td>
        <td><%= customer.location %></td>
        <td><%= customer.current_provider %></td>
        <td><%= customer.requirement %></td>
        <td><%= customer.remarks %></td>
        <td><%= customer.review %></td>
        <td><%= customer.rating %></td>
        <td><%= customer.suggestions %></td>
        <td><%= customer.insights %></td>
        <td><%= customer.to_do %></td>
        <td><%= customer.last_communication %></td>
        <td><%= customer.call_back %></td>
        <td><%= customer.status %></td>
        <td><%= customer.discounts %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<table class="responstable">
  <tr>
    <th><strong>Name</strong></th>
    <th><%= @customer.name %></th>
  </tr>
  <tr>
    <td><strong>Contact number</strong></td>
    <td><%= @customer.contact_number %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>